# Generated by Django 4.1.2 on 2022-10-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0002_categories_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
