# Generated by Django 4.1.2 on 2022-10-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ink_Spot', '0003_remove_product_categories_delete_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='Uploads\\product')),
                ('categories', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ink_Spot.categories')),
            ],
        ),
    ]
