# Generated by Django 4.1.1 on 2022-10-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('a_uth', models.CharField(max_length=40)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='Uploads\\Books')),
                ('image_1', models.ImageField(upload_to='Uploads\\Books')),
                ('image_2', models.ImageField(upload_to='Uploads\\Books')),
                ('desc', models.CharField(max_length=500)),
                ('b_categories', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ink_Spot.b_categories')),
            ],
        ),
    ]
