# Generated by Django 4.1.7 on 2023-06-24 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ink_Spot', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ink_Spot.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ink_Spot.product')),
            ],
        ),
    ]
